name: Build Rolling (Ubuntu 24.04)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: rolling
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libeigen3-dev ros-rolling-ament-package
      - name: Configure workspace
        run: |
          mkdir -p ~/colcon_ws/src
          cd ~/colcon_ws
          ln -s ${GITHUB_WORKSPACE} src/px4_ros2_ctrl
          git clone https://github.com/PX4/px4_msgs.git -b main src/px4_msgs
      - name: Build px4_msgs
        run: |
          source /opt/ros/rolling/setup.bash
          cd ~/colcon_ws
          colcon build --packages-select px4_msgs --cmake-args -DCMAKE_BUILD_TYPE=RELWITHDEBINFO --symlink-install
      - name: Build px4_ros2_ctrl
        run: |
          source /opt/ros/rolling/setup.bash
          cd ~/colcon_ws
          colcon build --packages-select px4_ros2_ctrl --cmake-args -DCMAKE_BUILD_TYPE=RELWITHDEBINFO --symlink-install
