name: Build and Test package

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: "ROS 2 ${{ matrix.ros2_distro }}"
    runs-on: ubuntu-22.04
    container: px4io/px4-dev-ros2-${{ matrix.ros2_distro }}:latest
    strategy:
      fail-fast: false
      matrix:
        ros2_distro: [foxy, galactic, humble, rolling]
    steps:
      - uses: actions/checkout@v4
      - name: Configure workspace
        run: |
          unset ROS_DISTRO
          mkdir -p ~/colcon_ws/src
          cd ~/colcon_ws
          ln -s ${GITHUB_WORKSPACE} src/px4_ros2_ctrl
          git clone https://github.com/PX4/px4_msgs.git -b main src/px4_msgs
      - name: Build px4_msgs
        run: |
          source /opt/ros/${{ matrix.ros2_distro }}/setup.bash
          cd ~/colcon_ws
          colcon build --packages-select px4_msgs --cmake-args -DCMAKE_BUILD_TYPE=RELWITHDEBINFO --symlink-install
      - name: Build px4_ros2_ctrl
        run: |
          source /opt/ros/${{ matrix.ros2_distro }}/setup.bash
          cd ~/colcon_ws
          colcon build --packages-select px4_ros2_ctrl --cmake-args -DCMAKE_BUILD_TYPE=RELWITHDEBINFO --symlink-install
